/**
 * Gyin-O-Poly board, prices, and card decks.
 * Tweak numbers here to rebalance the game — no logic changes needed.
 */

export const CONFIG = {
  minPlayers: 2,
  maxPlayers: 4,
  startMoney: 1_500_000,
  goSalary: 200_000,
  jailFine: 50_000,
  jailMaxTurns: 3,
  incomeTax: 200_000,
  luxuryTax: 100_000,
  tokenStepMs: 220,
  boardTiles: 40,
};

export const PLAYER_PALETTE = [
  { id: "jade", hex: "#1f8a62", label: "ကျောက်စိမ်း", labelEn: "Jade" },
  { id: "gold", hex: "#d4a017", label: "ရွှေ", labelEn: "Gold" },
  { id: "ruby", hex: "#c44536", label: "ပတ္တမြား", labelEn: "Ruby" },
  { id: "sapphire", hex: "#2b6cb0", label: "နီလာ", labelEn: "Sapphire" },
];

export const DEFAULT_NAMES = ["ကိုမြို", "မသီရိ", "ကိုဇော်", "မအိ"];

/** Color-group metadata. upgradeCost is the price of one Wi-Fi router (or the Generator). */
export const GROUPS = {
  "street-food": {
    id: "street-food",
    label: "လမ်းဘေးအစားအစာ",
    labelEn: "Street Food",
    color: "#8b5a2b",
    upgradeCost: 50_000,
  },
  "tea-shops": {
    id: "tea-shops",
    label: "လက်ဖက်ရည်ဆိုင်",
    labelEn: "Tea Shops",
    color: "#7eb6d6",
    upgradeCost: 50_000,
  },
  mookata: {
    id: "mookata",
    label: "မူကတ",
    labelEn: "Mookata",
    color: "#d48bb0",
    upgradeCost: 100_000,
  },
  nightlife: {
    id: "nightlife",
    label: "ညဈေး",
    labelEn: "Night Markets",
    color: "#e07a3d",
    upgradeCost: 100_000,
  },
  markets: {
    id: "markets",
    label: "ဈေးကြီး",
    labelEn: "Grand Markets",
    color: "#c0392b",
    upgradeCost: 150_000,
  },
  malls: {
    id: "malls",
    label: "စျေးဝယ်စင်တာ",
    labelEn: "Malls",
    color: "#e2c044",
    upgradeCost: 150_000,
  },
  condos: {
    id: "condos",
    label: "ကွန်ဒို",
    labelEn: "Luxury Condos",
    color: "#2f7d4a",
    upgradeCost: 200_000,
  },
  "golden-mile": {
    id: "golden-mile",
    label: "ရွှေလမ်းမ",
    labelEn: "Golden Mile",
    color: "#1d3557",
    upgradeCost: 200_000,
  },
  transit: {
    id: "transit",
    label: "သယ်ယူပို့ဆောင်ရေး",
    labelEn: "Transit",
    color: "#3d3d3d",
    upgradeCost: 0,
  },
  utility: {
    id: "utility",
    label: "အများသုံးဝန်ဆောင်မှု",
    labelEn: "Utilities",
    color: "#5c6b73",
    upgradeCost: 0,
  },
};

/**
 * Classic 40-tile perimeter, clockwise from GO (bottom-right).
 * Property rents: [base, 1 router, 2, 3, 4, generator]. rentSet is monopoly with 0 upgrades.
 * Transit rents: index = number owned (1–4).
 */
export const TILES = [
  {
    id: 0,
    type: "go",
    name: "လစာဝင်ပြီ",
    nameEn: "Payday",
    short: "လစာ",
    subtitle: "Collect 200,000 Ks",
  },
  {
    id: 1,
    type: "property",
    group: "street-food",
    name: "မုန့်ဟင်းခါးဆိုင်",
    nameEn: "Mohinga Stall",
    short: "မုန့်ဟင်းခါး",
    price: 60_000,
    rent: 2_000,
    rentSet: 4_000,
    rents: [2_000, 10_000, 30_000, 90_000, 160_000, 250_000],
  },
  {
    id: 2,
    type: "gyin",
    name: "ဂျင်း",
    nameEn: "Gyin",
    subtitle: "Draw a setback",
  },
  {
    id: 3,
    type: "property",
    group: "street-food",
    name: "ပလာတာဆိုင်",
    nameEn: "Palata Stall",
    price: 60_000,
    rent: 4_000,
    rentSet: 8_000,
    rents: [4_000, 20_000, 60_000, 180_000, 320_000, 450_000],
  },
  {
    id: 4,
    type: "tax",
    name: "ဝင်ငွေခွန်",
    nameEn: "Income Tax",
    amount: 200_000,
  },
  {
    id: 5,
    type: "transit",
    group: "transit",
    name: "YBS",
    nameEn: "Yangon Bus Service",
    price: 200_000,
    rents: [25_000, 50_000, 100_000, 200_000],
  },
  {
    id: 6,
    type: "property",
    group: "tea-shops",
    name: "လက်ဖက်ရည်ကြမ်း",
    nameEn: "Strong Tea Shop",
    price: 100_000,
    rent: 6_000,
    rentSet: 12_000,
    rents: [6_000, 30_000, 90_000, 270_000, 400_000, 550_000],
  },
  {
    id: 7,
    type: "kyaw",
    name: "၉ ကျော်တယ်",
    nameEn: "9 Kyaw Tal",
    subtitle: "Draw a flex",
  },
  {
    id: 8,
    type: "property",
    group: "tea-shops",
    name: "မုန့်တီဆိုင်",
    nameEn: "Mont Di Shop",
    price: 100_000,
    rent: 6_000,
    rentSet: 12_000,
    rents: [6_000, 30_000, 90_000, 270_000, 400_000, 550_000],
  },
  {
    id: 9,
    type: "property",
    group: "tea-shops",
    name: "နာနတ်သီးရှေ့",
    nameEn: "Nanat Thii Corner",
    short: "နာနတ်သီး",
    price: 120_000,
    rent: 8_000,
    rentSet: 16_000,
    rents: [8_000, 40_000, 100_000, 300_000, 450_000, 600_000],
  },
  {
    id: 10,
    type: "jail",
    name: "ရွာပြင်ရောက်မယ်",
    nameEn: "Village Exile",
    short: "ရွာပြင်",
    subtitle: "Just visiting — unless you were sent",
  },
  {
    id: 11,
    type: "property",
    group: "mookata",
    name: "ကိုရီးယားမူကတ",
    nameEn: "Korean Mookata",
    short: "ကိုရီးယား",
    price: 140_000,
    rent: 10_000,
    rentSet: 20_000,
    rents: [10_000, 50_000, 150_000, 450_000, 625_000, 750_000],
  },
  {
    id: 12,
    type: "utility",
    group: "utility",
    name: "EPC မီတာဘေလ်",
    nameEn: "EPC Meter Bill",
    short: "EPC မီတာ",
    price: 150_000,
  },
  {
    id: 13,
    type: "property",
    group: "mookata",
    name: "BBQ Garden",
    nameEn: "BBQ Garden",
    price: 140_000,
    rent: 10_000,
    rentSet: 20_000,
    rents: [10_000, 50_000, 150_000, 450_000, 625_000, 750_000],
  },
  {
    id: 14,
    type: "property",
    group: "mookata",
    name: "ပင်လယ်စာမူကတ",
    nameEn: "Seafood Mookata",
    short: "ပင်လယ်စာ",
    price: 160_000,
    rent: 12_000,
    rentSet: 24_000,
    rents: [12_000, 60_000, 180_000, 500_000, 700_000, 900_000],
  },
  {
    id: 15,
    type: "transit",
    group: "transit",
    name: "Grab",
    nameEn: "Grab",
    price: 200_000,
    rents: [25_000, 50_000, 100_000, 200_000],
  },
  {
    id: 16,
    type: "property",
    group: "nightlife",
    name: "၁၉လမ်းညဈေး",
    nameEn: "19th Street",
    short: "၁၉လမ်း",
    price: 180_000,
    rent: 14_000,
    rentSet: 28_000,
    rents: [14_000, 70_000, 200_000, 550_000, 750_000, 950_000],
  },
  {
    id: 17,
    type: "gyin",
    name: "ဂျင်း",
    nameEn: "Gyin",
    subtitle: "Draw a setback",
  },
  {
    id: 18,
    type: "property",
    group: "nightlife",
    name: "ကြည့်မြင်တိုင်ညဈေး",
    nameEn: "Kyi Myin Daing Night",
    short: "ကြည့်မြင်တိုင်",
    price: 180_000,
    rent: 14_000,
    rentSet: 28_000,
    rents: [14_000, 70_000, 200_000, 550_000, 750_000, 950_000],
  },
  {
    id: 19,
    type: "property",
    group: "nightlife",
    name: "တရုတ်တန်းည",
    nameEn: "Chinatown Night",
    price: 200_000,
    rent: 16_000,
    rentSet: 32_000,
    rents: [16_000, 80_000, 220_000, 600_000, 800_000, 1_000_000],
  },
  {
    id: 20,
    type: "safe",
    name: "မီးလာပြီဟေ့",
    nameEn: "Power's Back",
    short: "မီးလာပြီ",
    subtitle: "Safe zone — collect the pot",
  },
  {
    id: 21,
    type: "property",
    group: "markets",
    name: "ဗိုလ်ချုပ်ဈေး",
    nameEn: "Bogyoke Market",
    short: "ဗိုလ်ချုပ်",
    price: 220_000,
    rent: 18_000,
    rentSet: 36_000,
    rents: [18_000, 90_000, 250_000, 700_000, 875_000, 1_050_000],
  },
  {
    id: 22,
    type: "kyaw",
    name: "၉ ကျော်တယ်",
    nameEn: "9 Kyaw Tal",
    subtitle: "Draw a flex",
  },
  {
    id: 23,
    type: "property",
    group: "markets",
    name: "သိမ်ကြီးဈေး",
    nameEn: "Theingyi Market",
    short: "သိမ်ကြီး",
    price: 220_000,
    rent: 18_000,
    rentSet: 36_000,
    rents: [18_000, 90_000, 250_000, 700_000, 875_000, 1_050_000],
  },
  {
    id: 24,
    type: "property",
    group: "markets",
    name: "သိမ်ဖြူဈေး",
    nameEn: "Thein Phyu Market",
    short: "သိမ်ဖြူ",
    price: 240_000,
    rent: 20_000,
    rentSet: 40_000,
    rents: [20_000, 100_000, 300_000, 750_000, 925_000, 1_100_000],
  },
  {
    id: 25,
    type: "transit",
    group: "transit",
    name: "Bolt",
    nameEn: "Bolt",
    price: 200_000,
    rents: [25_000, 50_000, 100_000, 200_000],
  },
  {
    id: 26,
    type: "property",
    group: "malls",
    name: "Junction City",
    nameEn: "Junction City",
    short: "Junction",
    price: 260_000,
    rent: 22_000,
    rentSet: 44_000,
    rents: [22_000, 110_000, 330_000, 800_000, 975_000, 1_150_000],
  },
  {
    id: 27,
    type: "property",
    group: "malls",
    name: "Myanmar Plaza",
    nameEn: "Myanmar Plaza",
    short: "Plaza",
    price: 260_000,
    rent: 22_000,
    rentSet: 44_000,
    rents: [22_000, 110_000, 330_000, 800_000, 975_000, 1_150_000],
  },
  {
    id: 28,
    type: "utility",
    group: "utility",
    name: "YCDC ရေဘေလ်",
    nameEn: "City Water Bill",
    short: "ရေဘေလ်",
    price: 150_000,
  },
  {
    id: 29,
    type: "property",
    group: "malls",
    name: "City Mall",
    nameEn: "City Mall",
    price: 280_000,
    rent: 24_000,
    rentSet: 48_000,
    rents: [24_000, 120_000, 360_000, 850_000, 1_025_000, 1_200_000],
  },
  {
    id: 30,
    type: "gotojail",
    name: "ရွာပြင်ပို့ခံရ",
    nameEn: "Sent to the Village",
    short: "ရွာပြင်ပို့",
    subtitle: "Do not collect payday",
  },
  {
    id: 31,
    type: "property",
    group: "condos",
    name: "Star City",
    nameEn: "Star City",
    price: 300_000,
    rent: 26_000,
    rentSet: 52_000,
    rents: [26_000, 130_000, 390_000, 900_000, 1_100_000, 1_275_000],
  },
  {
    id: 32,
    type: "property",
    group: "condos",
    name: "ကန်သာယာ",
    nameEn: "Kantharyar Residence",
    short: "ကန်သာယာ",
    price: 300_000,
    rent: 26_000,
    rentSet: 52_000,
    rents: [26_000, 130_000, 390_000, 900_000, 1_100_000, 1_275_000],
  },
  {
    id: 33,
    type: "gyin",
    name: "ဂျင်း",
    nameEn: "Gyin",
    subtitle: "Draw a setback",
  },
  {
    id: 34,
    type: "property",
    group: "condos",
    name: "Time City",
    nameEn: "Time City",
    price: 320_000,
    rent: 28_000,
    rentSet: 56_000,
    rents: [28_000, 150_000, 450_000, 1_000_000, 1_200_000, 1_400_000],
  },
  {
    id: 35,
    type: "transit",
    group: "transit",
    name: "ရထားဝိုင်း",
    nameEn: "Circular Railway",
    short: "ရထားဝိုင်း",
    price: 200_000,
    rents: [25_000, 50_000, 100_000, 200_000],
  },
  {
    id: 36,
    type: "kyaw",
    name: "၉ ကျော်တယ်",
    nameEn: "9 Kyaw Tal",
    subtitle: "Draw a flex",
  },
  {
    id: 37,
    type: "property",
    group: "golden-mile",
    name: "ကန်တော်ကြီးရှုခင်း",
    nameEn: "Kandawgyi View",
    short: "ကန်တော်ကြီး",
    price: 350_000,
    rent: 35_000,
    rentSet: 70_000,
    rents: [35_000, 175_000, 500_000, 1_100_000, 1_300_000, 1_500_000],
  },
  {
    id: 38,
    type: "tax",
    name: "အထူးခွန်",
    nameEn: "Luxury Tax",
    amount: 100_000,
  },
  {
    id: 39,
    type: "property",
    group: "golden-mile",
    name: "ရွှေတိဂုံထိပ်ခန်း",
    nameEn: "Shwedagon Penthouse",
    short: "ရွှေတိဂုံ",
    price: 400_000,
    rent: 50_000,
    rentSet: 100_000,
    rents: [50_000, 200_000, 600_000, 1_400_000, 1_700_000, 2_000_000],
  },
];

/** Penalties and setbacks. Draw from the Gyin pile. */
export const GYIN_DECK = [
  {
    id: "say-htoe",
    title: "ဆေထိုးခံရပြီ",
    titleEn: "Say Htoe Khan Ya B",
    body: "သူငယ်ချင်းက ဆေထိုးလိုက်တယ်။ ၃၀,၀၀၀ ကျပ် ပေးလိုက်ပါ။",
    effect: { type: "pay", amount: 30_000 },
  },
  {
    id: "plugged-kyoot",
    title: "ပလပ်ကျွတ်",
    titleEn: "Plugged Kyoot",
    body: "ပလပ်ကျွတ်သွားလို့ အလုပ်မဖြစ်။ နောက်အလှည့် ကျော်ရမယ်။",
    effect: { type: "skip" },
  },
  {
    id: "village-bus",
    title: "ရွာပြင်ပို့ခံရ",
    titleEn: "Exiled to the Village",
    body: "ဂျင်းကြီးလွန်းလို့ ရွာပြင်ပို့ခံရပြီ။ လစာမယူရ။",
    effect: { type: "gotoJail" },
  },
  {
    id: "ybs-break",
    title: "YBS ပြတ်သွားပြီ",
    titleEn: "YBS Broke Down",
    body: "ဘတ်စ်ကားပျက်။ ၃ ကွက် ပြန်ဆုတ်။",
    effect: { type: "moveRelative", steps: -3 },
  },
  {
    id: "gen-died",
    title: "ဂျင်နရေတာသေပြီ",
    titleEn: "Generator Died",
    body: "မီးပြတ်ပြီး ဂျင်နရေတာပါ သေ။ ၄၀,၀၀၀ ကျပ် ပေး။",
    effect: { type: "pay", amount: 40_000 },
  },
  {
    id: "wifi-cut",
    title: "Wi-Fi ပြတ်",
    titleEn: "Wi-Fi Cut",
    body: "လုပ်ငန်းခွင် အင်တာနက်ပြတ်။ ၂၀,၀၀၀ ကျပ် ပေး။",
    effect: { type: "pay", amount: 20_000 },
  },
  {
    id: "flood",
    title: "ရေကြီးပြီ",
    titleEn: "Street Flood",
    body: "မိုးရေကြီးလို့ ဆိုင်ပိတ်ရ။ ၂၅,၀၀၀ ကျပ် ထိခိုက်။",
    effect: { type: "pay", amount: 25_000 },
  },
  {
    id: "phone-snatch",
    title: "ဖုန်းပြုတ်",
    titleEn: "Phone Snatch",
    body: "ညဈေးမှာ ဖုန်းပြုတ်။ ၅၀,၀၀၀ ကျပ် ဆုံး။",
    effect: { type: "pay", amount: 50_000 },
  },
  {
    id: "meter-audit",
    title: "မီတာစစ်ဆေး",
    titleEn: "Meter Audit",
    body: "EPC က စစ်လာတယ်။ Wi-Fi router တစ်လုံးကို ၁၅,၀၀၀၊ Generator ကို ၄၀,၀၀၀ ပေး။",
    effect: { type: "repairs", router: 15_000, generator: 40_000 },
  },
  {
    id: "shop-rent",
    title: "ဆိုင်ခန်းငှားရမ်းခ",
    titleEn: "Shop Lease Due",
    body: "ပိုင်ရှင်က ငှားရမ်းခတောင်း။ ၈၀,၀၀၀ ကျပ် ပေး။",
    effect: { type: "pay", amount: 80_000 },
  },
  {
    id: "flat-tire",
    title: "တာယာပေါက်",
    titleEn: "Flat Tire",
    body: "လမ်းမှာ တာယာပေါက်။ ၂ ကွက် ပြန်ဆုတ်။",
    effect: { type: "moveRelative", steps: -2 },
  },
  {
    id: "grab-surge",
    title: "Grab Surge",
    titleEn: "Grab Surge Pricing",
    body: "မိုးရွာလို့ စျေးတက်။ ၁၅,၀၀၀ ကျပ် ပေး။",
    effect: { type: "pay", amount: 15_000 },
  },
  {
    id: "rain-jam",
    title: "လမ်းပိတ်",
    titleEn: "Monsoon Jam",
    body: "မိုးကြောင့် လမ်းပိတ်။ နောက်အလှည့် ကျော်ရမယ်။",
    effect: { type: "skip" },
  },
  {
    id: "treat-round",
    title: "သူငယ်ချင်းပွဲ",
    titleEn: "You Are Paying",
    body: "ကုန်ကျစရိတ် သင့်အလှည့်။ ကစားသမားတိုင်းကို ၁၀,၀၀၀ ကျပ် ပေး။",
    effect: { type: "payEach", amount: 10_000 },
  },
  {
    id: "parking-fine",
    title: "ကားရပ်ဒဏ်ကြေး",
    titleEn: "Parking Fine",
    body: "မှားရပ်လို့ ဒဏ်ကြေး။ ၃၅,၀၀၀ ကျပ်။",
    effect: { type: "pay", amount: 35_000 },
  },
  {
    id: "go-to-epc",
    title: "မီတာသွားပေး",
    titleEn: "Pay the Meter",
    body: "EPC ရုံးကို သွား။ လမ်းမှာ လစာကွက်ကျရင် ယူလို့ရ။",
    effect: { type: "moveTo", tileId: 12, collectGo: true },
  },
];

/** Rewards and flexes. Draw from the 9 Kyaw Tal pile. */
export const KYAW_DECK = [
  {
    id: "dai-sho",
    title: "ဒိုင်ရှိုး",
    titleEn: "Dai Sho",
    body: "ဒိုင်ရှိုးကြီးပဲ။ ဘဏ်က ၅၀,၀၀၀ ကျပ် ထုတ်ပေးတယ်။",
    effect: { type: "collect", amount: 50_000 },
  },
  {
    id: "skb",
    title: "SKB Status",
    titleEn: "SKB Status",
    body: "SKB ပဲ။ ကစားသမားတိုင်းဆီက ၁၀,၀၀၀ ကျပ် ကောက်။",
    effect: { type: "collectFromEach", amount: 10_000 },
  },
  {
    id: "raise",
    title: "လစာတိုး",
    titleEn: "Salary Bump",
    body: "အလုပ်မှာ တိုးမြှင့်ခံရ။ ၁၀၀,၀၀၀ ကျပ် ရ။",
    effect: { type: "collect", amount: 100_000 },
  },
  {
    id: "longyi-cash",
    title: "လုံချည်ထဲပိုက်ဆံ",
    titleEn: "Cash in the Longyi",
    body: "လုံချည်အိတ်ထဲ ပိုက်ဆံတွေ့။ ၂၅,၀၀၀ ကျပ်။",
    effect: { type: "collect", amount: 25_000 },
  },
  {
    id: "village-pass",
    title: "ရွာပြင်လွတ်ကတ်",
    titleEn: "Village Pass",
    body: "ရွာပြင်က လွတ်ဖို့ ကတ်တစ်ခုရပြီ။ လိုတဲ့အခါ သုံး။",
    effect: { type: "jailPass" },
  },
  {
    id: "birthday",
    title: "မွေးနေ့ပွဲ",
    titleEn: "Birthday Treat",
    body: "မွေးနေ့မို့ သူငယ်ချင်းတွေက ထည့်ကြတယ်။ တစ်ယောက် ၁၅,၀၀၀။",
    effect: { type: "collectFromEach", amount: 15_000 },
  },
  {
    id: "advance-go",
    title: "လစာကွက်သို့",
    titleEn: "Advance to Payday",
    body: "လစာကွက်ကို တန်းသွား။ ၂၀၀,၀၀၀ ကျပ် ယူ။",
    effect: { type: "moveTo", tileId: 0, collectGo: true },
  },
  {
    id: "nearest-ride",
    title: "အနီးဆုံးယာဉ်",
    titleEn: "Nearest Ride",
    body: "အနီးဆုံး YBS / Grab / Bolt / ရထားဝိုင်း သို့ သွား။",
    effect: { type: "nearest", kind: "transit" },
  },
  {
    id: "bank-error",
    title: "ဘဏ်အမှား",
    titleEn: "Bank Error in Your Favour",
    body: "KBZ က အမှားလုပ်။ ၇၅,၀၀၀ ကျပ် ဝင်။",
    effect: { type: "collect", amount: 75_000 },
  },
  {
    id: "pageant",
    title: "ချစ်တီးဆု",
    titleEn: "Thingyan Flex",
    body: "သင်္ကြန်မှာ ချစ်တီးပွဲ နိုင်။ ၄၀,၀၀၀ ကျပ်။",
    effect: { type: "collect", amount: 40_000 },
  },
  {
    id: "side-hustle",
    title: "ဘေးလုပ်ငန်း",
    titleEn: "Side Hustle",
    body: "ညမှာ Grab ကားမောင်း။ ၃၀,၀၀၀ ကျပ် ရ။",
    effect: { type: "collect", amount: 30_000 },
  },
  {
    id: "go-junction",
    title: "Junction City သို့",
    titleEn: "Head to Junction City",
    body: "Junction City ကို တန်းသွား။ လစာကွက်ကျရင် ယူလို့ရ။",
    effect: { type: "moveTo", tileId: 26, collectGo: true },
  },
  {
    id: "inheritance",
    title: "အမွေ",
    titleEn: "Family Inheritance",
    body: "အစ်ကိုက ပိုက်ဆံပို့။ ၁၀၀,၀၀၀ ကျပ်။",
    effect: { type: "collect", amount: 100_000 },
  },
  {
    id: "nearest-util",
    title: "ဘေလ်သွားပေး",
    titleEn: "Nearest Utility",
    body: "အနီးဆုံး မီတာ/ရေဘေလ် ကွက်သို့ သွား။",
    effect: { type: "nearest", kind: "utility" },
  },
  {
    id: "dividend",
    title: "အမြတ်ဝေစု",
    titleEn: "Tea Shop Dividend",
    body: "လက်ဖက်ရည်ဆိုင်က အမြတ်ခွဲ။ ၂၀,၀၀၀ ကျပ်။",
    effect: { type: "collect", amount: 20_000 },
  },
  {
    id: "free-upgrade",
    title: "Wi-Fi အလကား",
    titleEn: "Complimentary Router",
    body: "ပိုင်ဆိုင်ပြီးသား မြေကွက်တစ်ခုကို Wi-Fi router တစ်လုံး အလကား တပ်။ (မရှိရင် ၄၀,၀၀၀ ကျပ် ယူ)",
    effect: { type: "freeRouter" },
  },
];
